# Generated by Django 4.1.2 on 2022-10-17 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_album_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geeksmodel',
            name='img',
        ),
        migrations.RemoveField(
            model_name='geeksmodel',
            name='last_modified',
        ),
    ]
